"""initial schema

Revision ID: 001e8835a259
Revises: 
Create Date: 2026-09-25 22:38:51.266895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001e8835a259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create every table for the first version of the app."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_levels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_levels')),
    sa.UniqueConstraint('position', name=op.f('uq_learning_levels_position'))
    )
    op.create_table('practice_categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section_position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_categories'))
    )
    op.create_table('practice_sets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Enum('terms', 'speech', name='practice_set_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('grammar', 'lesson', 'pronunciation', 'vocabulary', name='practice_set_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('image_key', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('unit_label', sa.String(length=100), nullable=True),
    sa.Column('collection_title', sa.String(length=100), nullable=True),
    sa.Column('collection_subtitle', sa.String(length=200), nullable=True),
    sa.Column('collection_emoji', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_sets'))
    )
    op.create_table('tutors',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutors'))
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('grammar', 'lesson', 'pronunciation', 'vocabulary', name='lesson_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('image_key', sa.String(length=100), nullable=True),
    sa.Column('level_id', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['learning_levels.id'], name=op.f('fk_lessons_level_id_learning_levels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('level_id', 'position', name=op.f('uq_lessons_level_id_position'))
    )
    op.create_index(op.f('ix_lessons_level_id'), 'lessons', ['level_id'], unique=False)
    op.create_table('practice_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['practice_sets.id'], name=op.f('fk_practice_terms_set_id_practice_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_terms')),
    sa.UniqueConstraint('set_id', 'slug', name=op.f('uq_practice_terms_set_id_slug'))
    )
    op.create_table('practice_topics',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('minutes > 0', name=op.f('ck_practice_topics_minutes_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['practice_categories.id'], name=op.f('fk_practice_topics_category_id_practice_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_topics'))
    )
    op.create_index(op.f('ix_practice_topics_category_id'), 'practice_topics', ['category_id'], unique=False)
    op.create_table('practice_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['practice_sets.id'], name=op.f('fk_practice_words_set_id_practice_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_words')),
    sa.UniqueConstraint('set_id', 'slug', name=op.f('uq_practice_words_set_id_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_goal_minutes BETWEEN 1 AND 240', name=op.f('ck_users_daily_goal_minutes_range')),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], name=op.f('fk_users_tutor_id_tutors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('daily_activity',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('practised_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_lessons', sa.Integer(), nullable=False),
    sa.CheckConstraint('completed_lessons >= 0', name=op.f('ck_daily_activity_completed_lessons_non_negative')),
    sa.CheckConstraint('practised_seconds >= 0', name=op.f('ck_daily_activity_practised_seconds_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'activity_date', name=op.f('pk_daily_activity'))
    )
    op.create_table('lesson_completions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_completions_lesson_id_lessons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lesson_completions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lesson_id', name=op.f('pk_lesson_completions'))
    )
    op.create_table('term_statuses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('still-learning', 'known', 'my-list', name='term_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['practice_terms.id'], name=op.f('fk_term_statuses_term_id_practice_terms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_term_statuses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'term_id', name=op.f('pk_term_statuses'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop every table (children first, because of foreign keys)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_statuses')
    op.drop_table('lesson_completions')
    op.drop_table('daily_activity')
    op.drop_table('users')
    op.drop_table('practice_words')
    op.drop_index(op.f('ix_practice_topics_category_id'), table_name='practice_topics')
    op.drop_table('practice_topics')
    op.drop_table('practice_terms')
    op.drop_index(op.f('ix_lessons_level_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('tutors')
    op.drop_table('practice_sets')
    op.drop_table('practice_categories')
    op.drop_table('learning_levels')
    # ### end Alembic commands ###
